### PR TITLE
Revision 1: update maintainer info

### PR DESCRIPTION
**Pull request by andreasabel**
Hello @IreneKnapp, we are using this package in hackage-server.
I propose to update the contact info (see changes) and make the respective Hackage revision.
Let me know if you are ok with this.

### CODE REVIEW

**Comment by andreasabel** [comment]
Ping @IreneKnapp

**Comment by IreneKnapp** [comment]
thanks for your patience. I'm pleased and surprised that anyone remembers this old package! yes, I'm happy to merge this change.

**Comment by andreasabel** [comment]
I pushed this to Hackage as revision 1: [hs-captcha-1.0-r1](https://hackage.haskell.org/package/hs-captcha-1.0/revisions)

**Comment by IreneKnapp** [comment]
thank you!

**Pull request merged**
